#!/usr/bin/env python3
"""Run local model CLIs in batches and write locked-output CSVs for Paper2."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import subprocess
import tempfile
import uuid
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path


REPO = Path(__file__).resolve().parents[2]
STEP5 = REPO / "data/04_extraction/05_llm_masem_substitution"
TEMPLATE = STEP5 / "locked_outputs/paper2_locked_output_template_20260606.csv"
OUTPUT_DIR = STEP5 / "locked_outputs/model_runs"
MANIFEST = STEP5 / "locked_outputs/LOCKED_OUTPUT_MANIFEST_20260606.csv"

PROMPT_VERSION = "paper2_task_family_prompt_v1_20260606"
SYSTEM_INSTRUCTIONS = """You are extracting structured answers for a meta-analysis validation task.
Use only the provided redacted task inputs. Do not infer from the human reference, because it is not provided.
Do not inspect the repository, use tools, search, read files, or explain a strategy.
Do not return Markdown, prose, plans, or code fences.
Return JSON only: an array of objects, one object per input task, preserving task_unit_id.
Each object must have these keys:
task_unit_id, model_answer, model_answer_normalized, model_source_locator, model_source_quote, model_confidence, abstained, error_code, notes.
If the source evidence is insufficient, set abstained=true, error_code=insufficient_evidence, and leave answer fields blank.
For numeric effect-size tasks, put the numeric value only in model_answer_normalized when possible.
Every input task_unit_id must appear exactly once in the returned array.
"""

ANSWER_FIELDS = [
    "task_unit_id",
    "model_answer",
    "model_answer_normalized",
    "model_source_locator",
    "model_source_quote",
    "model_confidence",
    "abstained",
    "error_code",
    "notes",
]


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, str]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def register_locked_output(path: Path) -> None:
    rows = read_csv(MANIFEST) if MANIFEST.exists() else []
    rows = [row for row in rows if row.get("file") != str(path)]
    rows.append(
        {
            "artifact_role": "locked_model_output",
            "file": str(path),
            "bytes": str(path.stat().st_size),
            "sha256": sha256(path),
            "locked_status": "locked_model_output",
            "notes": "Generated by scripts/llm_scoring_20260606/run_model_locked_output_batch.py.",
        }
    )
    write_csv(
        MANIFEST,
        rows,
        ["artifact_role", "file", "bytes", "sha256", "locked_status", "notes"],
    )


def extract_json_payload(text: str) -> list[dict[str, str]]:
    text = text.strip()
    candidates = [text]
    try:
        data = json.loads(text)
        if isinstance(data, dict):
            for key in ("result", "message", "response", "content", "text"):
                if isinstance(data.get(key), str):
                    candidates.append(data[key])
            if isinstance(data.get("answers"), list):
                return normalize_answers(data["answers"])
        elif isinstance(data, list):
            return normalize_answers(data)
    except json.JSONDecodeError:
        pass

    # Prefer provider payload strings over the outer CLI telemetry wrapper.
    for candidate in candidates[1:] + candidates[:1]:
        match = re.search(r"\[\s*\{.*\}\s*\]", candidate, flags=re.DOTALL)
        if match:
            return normalize_answers(json.loads(match.group(0)))
        match = re.search(r"\{.*\}", candidate, flags=re.DOTALL)
        if match:
            data = json.loads(match.group(0))
            if isinstance(data, dict) and isinstance(data.get("answers"), list):
                return normalize_answers(data["answers"])
    raise ValueError(f"No JSON answer array found in model output: {text[:500]}")


def normalize_answers(data: list[object]) -> list[dict[str, str]]:
    rows = []
    for item in data:
        if not isinstance(item, dict):
            continue
        rows.append({field: "" if item.get(field) is None else str(item.get(field, "")) for field in ANSWER_FIELDS})
    return rows


def prompt_for(rows: list[dict[str, str]]) -> str:
    tasks = []
    for row in rows:
        tasks.append(
            {
                "task_unit_id": row["task_unit_id"],
                "study_id": row["study_id"],
                "denominator_family": row["denominator_family"],
                "expected_answer_type": row["expected_answer_type"],
                "model_input_text": row["model_input_text"],
            }
        )
    return "\n".join(
        [
            SYSTEM_INSTRUCTIONS,
            "",
            "Tasks JSON:",
            json.dumps(tasks, ensure_ascii=False),
            "",
            "Return JSON array only.",
        ]
    )


def run_claude(prompt: str, timeout: int, max_budget_usd: str, model_selector: str) -> list[dict[str, str]]:
    cmd = [
        "claude",
        "-p",
        "--no-session-persistence",
        "--tools",
        "",
        "--permission-mode",
        "dontAsk",
        "--output-format",
        "json",
        "--max-budget-usd",
        max_budget_usd,
    ]
    if model_selector:
        cmd.extend(["--model", model_selector])
    cmd.append(prompt)
    completed = subprocess.run(cmd, text=True, capture_output=True, timeout=timeout)
    if completed.returncode != 0:
        raise RuntimeError(completed.stderr[-2000:] or completed.stdout[-2000:])
    return extract_json_payload(completed.stdout)


def run_gemini(prompt: str, timeout: int, model_selector: str) -> list[dict[str, str]]:
    cmd = [
        "gemini",
        "--prompt",
        prompt,
        "--output-format",
        "json",
        "--approval-mode",
        "plan",
    ]
    if model_selector:
        cmd.extend(["--model", model_selector])
    completed = subprocess.run(cmd, text=True, capture_output=True, timeout=timeout)
    if completed.returncode != 0:
        raise RuntimeError(completed.stderr[-2000:] or completed.stdout[-2000:])
    return extract_json_payload(completed.stdout)


def run_codex(prompt: str, timeout: int, model_selector: str) -> list[dict[str, str]]:
    with tempfile.NamedTemporaryFile("w+", suffix=".json", delete=False) as output:
        output_path = Path(output.name)
    cmd = [
        "codex",
        "exec",
        "--ephemeral",
    ]
    if model_selector:
        cmd.extend(["--model", model_selector])
    cmd.extend([
        "--ignore-user-config",
        "--skip-git-repo-check",
        "-C",
        tempfile.gettempdir(),
        "-s",
        "read-only",
        "-o",
        str(output_path),
        prompt,
    ])
    completed = subprocess.run(cmd, text=True, capture_output=True, timeout=timeout)
    text = output_path.read_text(encoding="utf-8", errors="replace")
    output_path.unlink(missing_ok=True)
    if completed.returncode != 0:
        raise RuntimeError(completed.stderr[-2000:] or completed.stdout[-2000:])
    return extract_json_payload(text or completed.stdout)


def eligible_rows(rows: list[dict[str, str]], families: set[str]) -> list[dict[str, str]]:
    selected = [
        row
        for row in rows
        if row["scoring_eligibility"].startswith("eligible_after_locked_llm_output")
        and (not families or row["denominator_family"] in families)
    ]
    return selected


def stratified_rows(rows: list[dict[str, str]], per_family: int) -> list[dict[str, str]]:
    buckets: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        if len(buckets[row["denominator_family"]]) < per_family:
            buckets[row["denominator_family"]].append(row)
    selected = []
    for family in sorted(buckets):
        selected.extend(buckets[family])
    return selected


def chunks(rows: list[dict[str, str]], size: int) -> list[list[dict[str, str]]]:
    return [rows[index:index + size] for index in range(0, len(rows), size)]


def failure_answers(rows: list[dict[str, str]], exc: Exception) -> list[dict[str, str]]:
    return [
        {
            "task_unit_id": row["task_unit_id"],
            "model_answer": "",
            "model_answer_normalized": "",
            "model_source_locator": "",
            "model_source_quote": "",
            "model_confidence": "",
            "abstained": "true",
            "error_code": "model_cli_error",
            "notes": str(exc)[:500],
        }
        for row in rows
    ]


def has_model_cli_error(rows: list[dict[str, str]]) -> bool:
    return any(row.get("error_code") == "model_cli_error" for row in rows)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--provider", choices=["claude", "gemini", "codex"], required=True)
    parser.add_argument("--run-id", default="")
    parser.add_argument("--families", default="", help="Comma-separated denominator families. Empty means all eligible families.")
    parser.add_argument("--stratified-per-family", type=int, default=0)
    parser.add_argument("--offset", type=int, default=0)
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--chunk-size", type=int, default=10)
    parser.add_argument("--timeout", type=int, default=240)
    parser.add_argument("--max-budget-usd", default="1.00")
    parser.add_argument("--model-selector", default="", help="Exact CLI model selector, e.g. sonnet, opus, gpt-5.5, gemini-2.5-pro.")
    parser.add_argument("--register", action="store_true")
    parser.add_argument(
        "--fail-on-model-cli-error",
        action="store_true",
        help="Exit nonzero when any row has model_cli_error, preventing wrapper loops from continuing.",
    )
    args = parser.parse_args()

    if args.chunk_size < 1:
        raise SystemExit("--chunk-size must be >= 1")

    families = {item.strip() for item in args.families.split(",") if item.strip()}
    template_rows = read_csv(TEMPLATE)
    selected = eligible_rows(template_rows, families)
    if args.stratified_per_family:
        selected = stratified_rows(selected, args.stratified_per_family)
    if args.offset:
        selected = selected[args.offset:]
    if args.limit:
        selected = selected[:args.limit]

    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    cli_meta = {
        "codex": ("openai", "codex_cli", subprocess.run(["codex", "--version"], text=True, capture_output=True).stdout.strip()),
        "claude": ("anthropic", "claude_code", subprocess.run(["claude", "--version"], text=True, capture_output=True).stdout.strip()),
        "gemini": ("google", "gemini_cli", subprocess.run(["gemini", "--version"], text=True, capture_output=True).stdout.strip()),
    }
    model_provider, cli_id, cli_version = cli_meta[args.provider]
    model_id = f"{args.provider}:{args.model_selector}" if args.model_selector else f"{cli_id}:default_unspecified"
    model_version = f"{cli_version}; model_selector={args.model_selector or 'default_unspecified'}"
    run_id = args.run_id or f"paper2_{args.provider}_batch_{now.replace(':', '').replace('-', '')}_{uuid.uuid4().hex[:8]}"

    output_rows = []
    for batch_number, batch in enumerate(chunks(selected, args.chunk_size), start=1):
        try:
            if args.provider == "claude":
                answers = run_claude(prompt_for(batch), args.timeout, args.max_budget_usd, args.model_selector)
            elif args.provider == "gemini":
                answers = run_gemini(prompt_for(batch), args.timeout, args.model_selector)
            else:
                answers = run_codex(prompt_for(batch), args.timeout, args.model_selector)
        except Exception as exc:
            answers = failure_answers(batch, exc)

        answer_by_id = {answer["task_unit_id"]: answer for answer in answers}
        for row in batch:
            answer = answer_by_id.get(row["task_unit_id"])
            if answer is None:
                answer = failure_answers([row], ValueError("missing_task_answer_from_batch"))[0]
            locked_row = dict(row)
            locked_row.update(
                {
                    "run_id": run_id,
                    "model_provider": model_provider,
                    "model_id": model_id,
                    "model_version": model_version,
                    "procedure_id": "raw_model_extraction_batch",
                    "prompt_version": PROMPT_VERSION,
                    "run_timestamp_utc": now,
                    "temperature": "0",
                    "seed": "",
                    "model_answer": answer.get("model_answer", ""),
                    "model_answer_normalized": answer.get("model_answer_normalized", ""),
                    "model_source_locator": answer.get("model_source_locator", ""),
                    "model_source_quote": answer.get("model_source_quote", ""),
                    "model_confidence": answer.get("model_confidence", ""),
                    "abstained": answer.get("abstained", ""),
                    "error_code": answer.get("error_code", ""),
                    "raw_output_ref": "not_persisted_batch",
                    "locked_answer_status": "locked",
                    "lock_timestamp_utc": now,
                    "locked_by": f"{args.provider}_cli_noninteractive_batch",
                    "notes": answer.get("notes", ""),
                }
            )
            output_rows.append(locked_row)
        print(f"batch={batch_number} rows={len(batch)} total_locked={len(output_rows)}", flush=True)

    output = OUTPUT_DIR / f"{run_id}.csv"
    write_csv(output, output_rows, list(template_rows[0].keys()))
    clean_for_manifest = not has_model_cli_error(output_rows)
    if args.register and clean_for_manifest:
        register_locked_output(output)
    print(output)
    print(f"rows={len(output_rows)}")
    print(f"registered={args.register and clean_for_manifest}")
    if args.register and not clean_for_manifest:
        print("register_skipped=model_cli_error")
    if args.fail_on_model_cli_error and not clean_for_manifest:
        raise SystemExit(2)


if __name__ == "__main__":
    main()
