#!/usr/bin/env python3
"""Run local model CLIs in batches and write locked-output CSVs for Paper2."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import re
import subprocess
import tempfile
import uuid
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from urllib import error, request


REPO = Path(__file__).resolve().parents[2]
STEP5 = REPO / "data/04_extraction/05_llm_masem_substitution"
DEFAULT_TEMPLATE = STEP5 / "locked_outputs/paper2_locked_output_template_20260606.csv"
DEFAULT_OUTPUT_DIR = STEP5 / "locked_outputs/model_runs"
DEFAULT_MANIFEST = STEP5 / "locked_outputs/LOCKED_OUTPUT_MANIFEST_20260606.csv"

DEFAULT_PROMPT_VERSION = "paper2_task_family_prompt_v1_20260606"
SYSTEM_INSTRUCTIONS = """You are extracting structured answers for a meta-analysis validation task.
Use only the provided redacted task inputs and any source-document packets included in the prompt. Do not infer from the human reference, because it is not provided.
Do not inspect the repository, use tools, search, read files, or explain a strategy.
Do not return Markdown, prose, plans, or code fences.
Return JSON only: an array of objects, one object per input task, preserving task_unit_id.
Each object must have these keys:
task_unit_id, model_answer, model_answer_normalized, model_source_locator, model_source_quote, model_confidence, abstained, error_code, notes.
If the source evidence is insufficient, set abstained=true, error_code=insufficient_evidence, and leave answer fields blank.
For numeric effect-size tasks, put the numeric value only in model_answer_normalized when possible.
Every input task_unit_id must appear exactly once in the returned array.
"""

ANSWER_FIELDS = [
    "task_unit_id",
    "model_answer",
    "model_answer_normalized",
    "model_source_locator",
    "model_source_quote",
    "model_confidence",
    "abstained",
    "error_code",
    "notes",
]


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def read_task_ids(path: Path) -> list[str]:
    if path.suffix.lower() == ".csv":
        with path.open(newline="", encoding="utf-8") as handle:
            reader = csv.DictReader(handle)
            if reader.fieldnames and "task_unit_id" in reader.fieldnames:
                return [row["task_unit_id"] for row in reader if row.get("task_unit_id")]
            if reader.fieldnames:
                first_field = reader.fieldnames[0]
                return [row[first_field] for row in reader if row.get(first_field)]
    return [line.strip() for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def write_csv(path: Path, rows: list[dict[str, str]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore", lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def register_locked_output(path: Path, manifest: Path) -> None:
    try:
        manifest_file = str(path.resolve().relative_to(REPO))
    except ValueError:
        manifest_file = str(path)
    rows = read_csv(manifest) if manifest.exists() else []
    rows = [
        row for row in rows
        if row.get("file") not in {str(path), str(path.resolve()), manifest_file}
    ]
    rows.append(
        {
            "artifact_role": "locked_model_output",
            "file": manifest_file,
            "bytes": str(path.stat().st_size),
            "sha256": sha256(path),
            "locked_status": "locked_model_output",
            "notes": "Generated by scripts/llm_scoring_20260606/run_model_locked_output_batch.py.",
        }
    )
    write_csv(
        manifest,
        rows,
        ["artifact_role", "file", "bytes", "sha256", "locked_status", "notes"],
    )


def extract_json_payload(text: str) -> list[dict[str, str]]:
    text = text.strip()
    candidates = [text]
    try:
        data = json.loads(text)
        if isinstance(data, dict):
            for key in ("result", "message", "response", "content", "text"):
                if isinstance(data.get(key), str):
                    candidates.append(data[key])
            if isinstance(data.get("answers"), list):
                return normalize_answers(data["answers"])
        elif isinstance(data, list):
            return normalize_answers(data)
    except json.JSONDecodeError:
        pass

    # Prefer provider payload strings over the outer CLI telemetry wrapper.
    for candidate in candidates[1:] + candidates[:1]:
        match = re.search(r"\[\s*\{.*\}\s*\]", candidate, flags=re.DOTALL)
        if match:
            return normalize_answers(json.loads(match.group(0)))
        match = re.search(r"\{.*\}", candidate, flags=re.DOTALL)
        if match:
            data = json.loads(match.group(0))
            if isinstance(data, dict) and isinstance(data.get("answers"), list):
                return normalize_answers(data["answers"])
    raise ValueError(f"No JSON answer array found in model output: {text[:500]}")


def normalize_answers(data: list[object]) -> list[dict[str, str]]:
    rows = []
    for item in data:
        if not isinstance(item, dict):
            continue
        rows.append({field: "" if item.get(field) is None else str(item.get(field, "")) for field in ANSWER_FIELDS})
    return rows


def load_source_packets(source_packet_dir: Path | None, rows: list[dict[str, str]]) -> dict[str, str]:
    if not source_packet_dir:
        return {}
    packets = {}
    for study_id in sorted({row["study_id"] for row in rows}):
        candidates = sorted(source_packet_dir.glob(f"{study_id}_source_packet*.txt"))
        candidates.extend(sorted(source_packet_dir.glob(f"{study_id}.txt")))
        if candidates:
            packets[study_id] = candidates[0].read_text(encoding="utf-8", errors="replace")
    return packets


def parse_model_input_field(text: str, label: str) -> str:
    match = re.search(rf"{re.escape(label)}:\s*([^|]+)", text)
    return match.group(1).strip() if match else ""


def load_task_route_overlay(path: Path | None) -> dict[str, dict[str, str]]:
    if not path:
        return {}
    overlays: dict[str, dict[str, str]] = {}
    for row in read_csv(path):
        task_id = row.get("task_unit_id", "")
        if not task_id:
            continue
        leakage_flag = (row.get("human_reference_value_in_prompt") or "").strip().lower()
        if leakage_flag not in {"", "false", "0", "no"}:
            raise SystemExit(f"Route overlay row may leak human reference value: {task_id}")
        overlays[task_id] = row
    return overlays


def route_config(route: str) -> tuple[str, str, str]:
    if route == "direct_r_effect_size_extraction":
        return (
            "numeric_r_effect_size",
            "primary_direct_r_or_source_reported_correlation",
            "Recover the source-reported direct/source r effect-size value for the requested construct pair. Prefer source correlation matrices, Fornell-Larcker/correlation tables, or explicit source-reported r tables. Do not use standardized beta/path coefficients unless the source explicitly labels the value as a direct/source r effect size. Abstain if no direct/source r evidence is present.",
        )
    if route == "latent_or_construct_correlation":
        return (
            "numeric_correlation_with_source_type",
            "primary_latent_or_construct_correlation_with_source_type_flag",
            "Recover the source-reported latent, construct, or interconstruct correlation for the requested construct pair. Prefer construct-correlation, Fornell-Larcker off-diagonal, or source-designated discriminant-validity value tables when they are the available source-value evidence. Do not use standardized beta/path coefficients. Include the source value type in model_answer and put the numeric value in model_answer_normalized.",
        )
    if route == "latent_or_construct_correlation_or_direct_source_value":
        return (
            "numeric_correlation_with_source_type",
            "non_path_source_value_route",
            "Recover the source-reported non-path value for the requested construct pair, such as a direct correlation, latent/construct correlation, interconstruct correlation, Fornell-Larcker off-diagonal value, or source-designated discriminant-validity value. Do not use standardized beta/path coefficients. Include the source value type in model_answer and put the numeric value in model_answer_normalized.",
        )
    if route == "beta_or_path_converted_effect_size":
        return (
            "numeric_effect_size_with_source_type",
            "secondary_beta_or_path_converted_effect_size",
            "Recover the standardized beta/path coefficient for the requested directed construct relationship. Use structural/path coefficient, hypothesis, or SEM/PLS path tables. Do not use correlation, Fornell-Larcker, HTMT, or discriminant-validity tables for this route. Include the source value type in model_answer and put the numeric value in model_answer_normalized.",
        )
    return (
        "numeric_effect_size_with_source_type",
        route or "unspecified_route",
        "Use the task route and source packet evidence to recover the requested numeric value. Abstain if the source evidence is insufficient.",
    )


def routed_model_input_text(row: dict[str, str], overlay: dict[str, str]) -> tuple[str, str, str]:
    route = overlay.get("recommended_model_input_route", "").strip()
    expected_type, prompt_family, instruction = route_config(route)
    original = row.get("model_input_text", "")
    sample = parse_model_input_field(original, "Sample/stratum") or "unspecified"
    construct_pair = parse_model_input_field(original, "Construct pair") or "unspecified"
    category = overlay.get("revised_smoke_category", "").strip() or "route_overlay"
    text = (
        f"Study: {row['study_id']} | Sample/stratum: {sample} | "
        f"Construct pair: {construct_pair} | Expected answer type: {expected_type} | "
        f"Prompt task route: {route} | Revised smoke category: {category} | "
        f"Route instruction: {instruction} "
        "Use only the locked source-document rendering/chunks for the authorized run condition. "
        "The human reference value and human-adjudicated source locator are intentionally excluded."
    )
    return text, expected_type, prompt_family


def apply_task_route_overlay(
    rows: list[dict[str, str]],
    overlays: dict[str, dict[str, str]],
    require_overlay: bool,
) -> list[dict[str, str]]:
    if not overlays:
        return rows
    routed_rows: list[dict[str, str]] = []
    for row in rows:
        task_id = row["task_unit_id"]
        overlay = overlays.get(task_id)
        if not overlay:
            if require_overlay:
                raise SystemExit(f"Missing required route overlay for task_unit_id={task_id}")
            routed_rows.append(row)
            continue
        routed = dict(row)
        model_input, expected_type, prompt_family = routed_model_input_text(routed, overlay)
        routed["model_input_text"] = model_input
        routed["expected_answer_type"] = expected_type
        routed["_prompt_denominator_family"] = prompt_family
        routed["_prompt_task_route"] = overlay.get("recommended_model_input_route", "").strip()
        routed["_revised_smoke_category"] = overlay.get("revised_smoke_category", "").strip()
        routed_rows.append(routed)
    return routed_rows


def prompt_for(
    rows: list[dict[str, str]],
    source_packets: dict[str, str] | None = None,
    suppress_source_quotes: bool = False,
) -> str:
    source_packets = source_packets or {}
    tasks = []
    for row in rows:
        task = {
            "task_unit_id": row["task_unit_id"],
            "study_id": row["study_id"],
            "denominator_family": row.get("_prompt_denominator_family", row["denominator_family"]),
            "expected_answer_type": row["expected_answer_type"],
            "model_input_text": row["model_input_text"],
        }
        if row.get("_prompt_task_route"):
            task["prompt_task_route"] = row["_prompt_task_route"]
        if row.get("_revised_smoke_category"):
            task["revised_smoke_category"] = row["_revised_smoke_category"]
        tasks.append(task)
    parts = [
        SYSTEM_INSTRUCTIONS,
        "",
    ]
    if suppress_source_quotes:
        parts.extend(
            [
                "Run-specific source-text safety policy:",
                "Do not reproduce source-document wording in model_source_quote. Set model_source_quote to blank and use model_source_locator for page/chunk IDs instead.",
                "",
            ]
        )
    if any(row.get("_prompt_task_route") for row in rows):
        parts.extend(
            [
                "Run-specific task-route overlay policy:",
                "Use each task's prompt_task_route and Route instruction in model_input_text as the active extraction target. If source-packet task stubs conflict with Tasks JSON, Tasks JSON supersedes the packet stubs.",
                "Never use a beta/path coefficient for a task routed as direct_r_effect_size_extraction, latent_or_construct_correlation, or latent_or_construct_correlation_or_direct_source_value.",
                "",
            ]
        )
    source_payload = {
        row["study_id"]: source_packets[row["study_id"]]
        for row in rows
        if row["study_id"] in source_packets
    }
    if source_payload:
        parts.extend(
            [
                "Source Packets JSON:",
                json.dumps(source_payload, ensure_ascii=False),
                "",
            ]
        )
    parts.extend(
        [
            "Tasks JSON:",
            json.dumps(tasks, ensure_ascii=False),
            "",
            "Return JSON array only.",
        ]
    )
    return "\n".join(parts)


def run_claude(prompt: str, timeout: int, max_budget_usd: str, model_selector: str) -> list[dict[str, str]]:
    cmd = [
        "claude",
        "-p",
        "--no-session-persistence",
        "--tools",
        "",
        "--permission-mode",
        "dontAsk",
        "--output-format",
        "json",
        "--max-budget-usd",
        max_budget_usd,
    ]
    if model_selector:
        cmd.extend(["--model", model_selector])
    cmd.append(prompt)
    completed = subprocess.run(cmd, text=True, capture_output=True, timeout=timeout)
    if completed.returncode != 0:
        raise RuntimeError(completed.stderr[-2000:] or completed.stdout[-2000:])
    return extract_json_payload(completed.stdout)


def run_gemini(prompt: str, timeout: int, model_selector: str) -> list[dict[str, str]]:
    cmd = [
        "gemini",
        "--prompt",
        prompt,
        "--output-format",
        "json",
        "--approval-mode",
        "plan",
    ]
    if model_selector:
        cmd.extend(["--model", model_selector])
    completed = subprocess.run(cmd, text=True, capture_output=True, timeout=timeout)
    if completed.returncode != 0:
        raise RuntimeError(completed.stderr[-2000:] or completed.stdout[-2000:])
    return extract_json_payload(completed.stdout)


def run_gemini_api(prompt: str, timeout: int, model_selector: str) -> list[dict[str, str]]:
    api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        raise RuntimeError("GEMINI_API_KEY or GOOGLE_API_KEY is required for gemini_api")
    model = model_selector or "gemini-3-flash-preview"
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent"
    payload = {
        "contents": [{"role": "user", "parts": [{"text": prompt}]}],
        "generationConfig": {"temperature": 0},
    }
    body = json.dumps(payload).encode("utf-8")
    req = request.Request(
        url,
        data=body,
        headers={
            "Content-Type": "application/json",
            "x-goog-api-key": api_key,
        },
        method="POST",
    )
    try:
        with request.urlopen(req, timeout=timeout) as response:
            data = json.loads(response.read().decode("utf-8"))
    except error.HTTPError as exc:
        text = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"Gemini API HTTP {exc.code}: {text[-2000:]}")
    parts = (
        data.get("candidates", [{}])[0]
        .get("content", {})
        .get("parts", [])
    )
    text = "\n".join(part.get("text", "") for part in parts if isinstance(part, dict))
    if not text:
        raise RuntimeError(f"Gemini API response had no text: {json.dumps(data)[:1000]}")
    return extract_json_payload(text)


def run_codex(prompt: str, timeout: int, model_selector: str) -> list[dict[str, str]]:
    with tempfile.NamedTemporaryFile("w+", suffix=".json", delete=False) as output:
        output_path = Path(output.name)
    cmd = [
        "codex",
        "exec",
        "--ephemeral",
    ]
    if model_selector:
        cmd.extend(["--model", model_selector])
    cmd.extend([
        "--ignore-user-config",
        "--skip-git-repo-check",
        "-C",
        tempfile.gettempdir(),
        "-s",
        "read-only",
        "-o",
        str(output_path),
        prompt,
    ])
    completed = subprocess.run(cmd, text=True, capture_output=True, timeout=timeout)
    text = output_path.read_text(encoding="utf-8", errors="replace")
    output_path.unlink(missing_ok=True)
    if completed.returncode != 0:
        raise RuntimeError(completed.stderr[-2000:] or completed.stdout[-2000:])
    return extract_json_payload(text or completed.stdout)


def eligible_rows(rows: list[dict[str, str]], families: set[str]) -> list[dict[str, str]]:
    selected = [
        row
        for row in rows
        if row["scoring_eligibility"].startswith("eligible_after_locked_llm_output")
        and (not families or row["denominator_family"] in families)
    ]
    return selected


def selected_task_rows(rows: list[dict[str, str]], task_ids: list[str]) -> list[dict[str, str]]:
    by_id = {row["task_unit_id"]: row for row in rows}
    missing = [task_id for task_id in task_ids if task_id not in by_id]
    if missing:
        raise SystemExit(f"Task IDs not found or ineligible: {', '.join(missing[:10])}")
    return [by_id[task_id] for task_id in task_ids]


def stratified_rows(rows: list[dict[str, str]], per_family: int) -> list[dict[str, str]]:
    buckets: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        if len(buckets[row["denominator_family"]]) < per_family:
            buckets[row["denominator_family"]].append(row)
    selected = []
    for family in sorted(buckets):
        selected.extend(buckets[family])
    return selected


def chunks(rows: list[dict[str, str]], size: int) -> list[list[dict[str, str]]]:
    return [rows[index:index + size] for index in range(0, len(rows), size)]


def failure_answers(rows: list[dict[str, str]], exc: Exception) -> list[dict[str, str]]:
    return [
        {
            "task_unit_id": row["task_unit_id"],
            "model_answer": "",
            "model_answer_normalized": "",
            "model_source_locator": "",
            "model_source_quote": "",
            "model_confidence": "",
            "abstained": "true",
            "error_code": "model_cli_error",
            "notes": str(exc)[:500],
        }
        for row in rows
    ]


def source_quote_policy_failure(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    answers = failure_answers(rows, RuntimeError("source_quote_policy_violation"))
    for answer in answers:
        answer["error_code"] = "source_quote_policy_violation"
        answer["notes"] = "Model returned source text despite suppress_source_quotes policy; output not registered."
    return answers


def has_manifest_blocking_error(rows: list[dict[str, str]]) -> bool:
    return any(row.get("error_code") in {"model_cli_error", "source_quote_policy_violation"} for row in rows)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--provider", choices=["claude", "gemini", "gemini_api", "codex"], required=True)
    parser.add_argument("--template", type=Path, default=DEFAULT_TEMPLATE)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--prompt-version", default=DEFAULT_PROMPT_VERSION)
    parser.add_argument("--procedure-id", default="raw_model_extraction_batch")
    parser.add_argument("--locked-by", default="", help="Override locked_by; default is provider_noninteractive_batch.")
    parser.add_argument("--run-id", default="")
    parser.add_argument("--families", default="", help="Comma-separated denominator families. Empty means all eligible families.")
    parser.add_argument("--study-ids", default="", help="Comma-separated study IDs. Empty means all eligible studies.")
    parser.add_argument("--task-ids-file", type=Path, default=None, help="CSV/text file listing task_unit_id values to run in file order.")
    parser.add_argument("--task-route-overlay", type=Path, default=None, help="Optional CSV keyed by task_unit_id with revised prompt route metadata.")
    parser.add_argument("--require-task-route-overlay", action="store_true", help="Fail if any selected task lacks a row in --task-route-overlay.")
    parser.add_argument("--stratified-per-family", type=int, default=0)
    parser.add_argument("--offset", type=int, default=0)
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--chunk-size", type=int, default=10)
    parser.add_argument("--timeout", type=int, default=240)
    parser.add_argument("--max-budget-usd", default="1.00")
    parser.add_argument("--model-selector", default="", help="Exact CLI model selector, e.g. sonnet, opus, gpt-5.5, gemini-2.5-pro.")
    parser.add_argument("--source-packet-dir", type=Path, default=None, help="Private directory containing {study_id}_source_packet*.txt files.")
    parser.add_argument("--require-source-packet", action="store_true", help="Fail if any selected row lacks a private source packet.")
    parser.add_argument("--suppress-source-quotes", action="store_true", help="Ask the model to leave model_source_quote blank and reject batches that violate it.")
    parser.add_argument("--register", action="store_true")
    parser.add_argument(
        "--fail-on-model-cli-error",
        action="store_true",
        help="Exit nonzero when any row has model_cli_error, preventing wrapper loops from continuing.",
    )
    args = parser.parse_args()

    if args.chunk_size < 1:
        raise SystemExit("--chunk-size must be >= 1")

    families = {item.strip() for item in args.families.split(",") if item.strip()}
    study_ids = {item.strip() for item in args.study_ids.split(",") if item.strip()}
    template_rows = read_csv(args.template)
    selected = eligible_rows(template_rows, families)
    if study_ids:
        selected = [row for row in selected if row["study_id"] in study_ids]
    if args.task_ids_file:
        selected = selected_task_rows(selected, read_task_ids(args.task_ids_file))
    elif args.stratified_per_family:
        selected = stratified_rows(selected, args.stratified_per_family)
    if args.offset:
        selected = selected[args.offset:]
    if args.limit:
        selected = selected[:args.limit]
    route_overlays = load_task_route_overlay(args.task_route_overlay)
    selected = apply_task_route_overlay(selected, route_overlays, args.require_task_route_overlay)
    source_packets = load_source_packets(args.source_packet_dir, selected)
    if args.require_source_packet:
        missing_packets = sorted({row["study_id"] for row in selected if row["study_id"] not in source_packets})
        if missing_packets:
            raise SystemExit(f"Missing required source packets for studies: {', '.join(missing_packets)}")

    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    cli_meta = {
        "codex": ("openai", "codex_cli", subprocess.run(["codex", "--version"], text=True, capture_output=True).stdout.strip()),
        "claude": ("anthropic", "claude_code", subprocess.run(["claude", "--version"], text=True, capture_output=True).stdout.strip()),
        "gemini": ("google", "gemini_cli", subprocess.run(["gemini", "--version"], text=True, capture_output=True).stdout.strip()),
        "gemini_api": ("google", "gemini_api", "generativelanguage.googleapis.com/v1beta"),
    }
    model_provider, cli_id, cli_version = cli_meta[args.provider]
    model_prefix = "gemini" if args.provider == "gemini_api" else args.provider
    model_id = f"{model_prefix}:{args.model_selector}" if args.model_selector else f"{cli_id}:default_unspecified"
    model_version = f"{cli_version}; model_selector={args.model_selector or 'default_unspecified'}"
    run_id = args.run_id or f"paper2_{args.provider}_batch_{now.replace(':', '').replace('-', '')}_{uuid.uuid4().hex[:8]}"

    output_rows = []
    for batch_number, batch in enumerate(chunks(selected, args.chunk_size), start=1):
        try:
            if args.provider == "claude":
                answers = run_claude(prompt_for(batch, source_packets, args.suppress_source_quotes), args.timeout, args.max_budget_usd, args.model_selector)
            elif args.provider == "gemini":
                answers = run_gemini(prompt_for(batch, source_packets, args.suppress_source_quotes), args.timeout, args.model_selector)
            elif args.provider == "gemini_api":
                answers = run_gemini_api(prompt_for(batch, source_packets, args.suppress_source_quotes), args.timeout, args.model_selector)
            else:
                answers = run_codex(prompt_for(batch, source_packets, args.suppress_source_quotes), args.timeout, args.model_selector)
        except Exception as exc:
            answers = failure_answers(batch, exc)
        if args.suppress_source_quotes and any(answer.get("model_source_quote", "").strip() for answer in answers):
            answers = source_quote_policy_failure(batch)

        answer_by_id = {answer["task_unit_id"]: answer for answer in answers}
        for row in batch:
            answer = answer_by_id.get(row["task_unit_id"])
            if answer is None:
                answer = failure_answers([row], ValueError("missing_task_answer_from_batch"))[0]
            locked_row = dict(row)
            locked_row.update(
                {
                    "run_id": run_id,
                    "model_provider": model_provider,
                    "model_id": model_id,
                    "model_version": model_version,
                    "procedure_id": args.procedure_id,
                    "prompt_version": args.prompt_version,
                    "run_timestamp_utc": now,
                    "temperature": "0",
                    "seed": "",
                    "model_answer": answer.get("model_answer", ""),
                    "model_answer_normalized": answer.get("model_answer_normalized", ""),
                    "model_source_locator": answer.get("model_source_locator", ""),
                    "model_source_quote": answer.get("model_source_quote", ""),
                    "model_confidence": answer.get("model_confidence", ""),
                    "abstained": answer.get("abstained", ""),
                    "error_code": answer.get("error_code", ""),
                    "raw_output_ref": "not_persisted_batch",
                    "locked_answer_status": "locked",
                    "lock_timestamp_utc": now,
                    "locked_by": args.locked_by or f"{args.provider}_noninteractive_batch",
                    "notes": answer.get("notes", ""),
                }
            )
            output_rows.append(locked_row)
        print(f"batch={batch_number} rows={len(batch)} total_locked={len(output_rows)}", flush=True)

    output = args.output_dir / f"{run_id}.csv"
    write_csv(output, output_rows, list(template_rows[0].keys()))
    clean_for_manifest = not has_manifest_blocking_error(output_rows)
    if args.register and clean_for_manifest:
        register_locked_output(output, args.manifest)
    print(output)
    print(f"rows={len(output_rows)}")
    print(f"registered={args.register and clean_for_manifest}")
    if args.register and not clean_for_manifest:
        print("register_skipped=model_cli_error")
    if args.fail_on_model_cli_error and not clean_for_manifest:
        raise SystemExit(2)


if __name__ == "__main__":
    main()
