#!/usr/bin/env python3
"""Run a local model CLI and write a locked-output CSV for Paper2 scoring."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import subprocess
import tempfile
import uuid
from datetime import datetime, timezone
from pathlib import Path


REPO = Path(__file__).resolve().parents[2]
STEP5 = REPO / "data/04_extraction/05_llm_masem_substitution"
TEMPLATE = STEP5 / "locked_outputs/paper2_locked_output_template_20260606.csv"
SCHEMA = STEP5 / "schemas/MODEL_ANSWER_SCHEMA_20260606.json"
OUTPUT_DIR = STEP5 / "locked_outputs/model_runs"
MANIFEST = STEP5 / "locked_outputs/LOCKED_OUTPUT_MANIFEST_20260606.csv"

PROMPT_VERSION = "paper2_task_family_prompt_v1_20260606"
SYSTEM_INSTRUCTIONS = """You are extracting one structured answer for a meta-analysis validation task.
Use only the provided redacted task input. Do not infer from the human reference, because it is not provided.
Return JSON only with these keys:
model_answer, model_answer_normalized, model_source_locator, model_source_quote, model_confidence, abstained, error_code, notes.
If the source evidence is insufficient, set abstained=true, error_code=insufficient_evidence, and leave answer fields blank.
For numeric effect-size tasks, put the numeric value only in model_answer_normalized when possible.
"""


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, str]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def register_locked_output(path: Path) -> None:
    rows = read_csv(MANIFEST) if MANIFEST.exists() else []
    rows = [row for row in rows if row.get("file") != str(path)]
    rows.append(
        {
            "artifact_role": "locked_model_output",
            "file": str(path),
            "bytes": str(path.stat().st_size),
            "sha256": sha256(path),
            "locked_status": "locked_model_output",
            "notes": "Generated by scripts/llm_scoring_20260606/run_model_locked_output.py.",
        }
    )
    write_csv(
        MANIFEST,
        rows,
        ["artifact_role", "file", "bytes", "sha256", "locked_status", "notes"],
    )


def extract_json(text: str) -> dict[str, str]:
    text = text.strip()
    try:
        data = json.loads(text)
        if isinstance(data, dict) and isinstance(data.get("result"), str):
            return extract_json(data["result"])
        if isinstance(data, dict) and isinstance(data.get("message"), str):
            return extract_json(data["message"])
        if isinstance(data, dict) and isinstance(data.get("response"), str):
            return extract_json(data["response"])
        if isinstance(data, dict):
            return {key: "" if value is None else str(value) for key, value in data.items()}
    except json.JSONDecodeError:
        pass
    match = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if not match:
        raise ValueError(f"No JSON object found in model output: {text[:500]}")
    data = json.loads(match.group(0))
    return {key: "" if value is None else str(value) for key, value in data.items()}


def prompt_for(row: dict[str, str]) -> str:
    return "\n".join(
        [
            SYSTEM_INSTRUCTIONS,
            "",
            "Task:",
            f"- task_unit_id: {row['task_unit_id']}",
            f"- study_id: {row['study_id']}",
            f"- denominator_family: {row['denominator_family']}",
            f"- expected_answer_type: {row['expected_answer_type']}",
            f"- model_input_text: {row['model_input_text']}",
            "",
            "Return JSON only.",
        ]
    )


def run_codex(prompt: str, timeout: int, model_selector: str) -> dict[str, str]:
    with tempfile.NamedTemporaryFile("w+", suffix=".json", delete=False) as output:
        output_path = Path(output.name)
    cmd = [
        "codex",
        "exec",
        "--ephemeral",
    ]
    if model_selector:
        cmd.extend(["--model", model_selector])
    cmd.extend([
        "-C",
        str(REPO),
        "-s",
        "read-only",
        "--output-schema",
        str(SCHEMA),
        "-o",
        str(output_path),
        prompt,
    ])
    completed = subprocess.run(cmd, text=True, capture_output=True, timeout=timeout)
    text = output_path.read_text(encoding="utf-8", errors="replace")
    output_path.unlink(missing_ok=True)
    if completed.returncode != 0:
        raise RuntimeError(completed.stderr[-2000:] or completed.stdout[-2000:])
    return extract_json(text or completed.stdout)


def run_claude(prompt: str, timeout: int, max_budget_usd: str, model_selector: str) -> dict[str, str]:
    cmd = [
        "claude",
        "-p",
        "--no-session-persistence",
        "--tools",
        "",
        "--permission-mode",
        "dontAsk",
        "--output-format",
        "json",
        "--max-budget-usd",
        max_budget_usd,
    ]
    if model_selector:
        cmd.extend(["--model", model_selector])
    cmd.append(prompt)
    completed = subprocess.run(cmd, text=True, capture_output=True, timeout=timeout)
    if completed.returncode != 0:
        raise RuntimeError(completed.stderr[-2000:] or completed.stdout[-2000:])
    return extract_json(completed.stdout)


def run_gemini(prompt: str, timeout: int, model_selector: str) -> dict[str, str]:
    cmd = [
        "gemini",
        "--prompt",
        prompt,
        "--output-format",
        "json",
        "--approval-mode",
        "plan",
    ]
    if model_selector:
        cmd.extend(["--model", model_selector])
    completed = subprocess.run(cmd, text=True, capture_output=True, timeout=timeout)
    if completed.returncode != 0:
        raise RuntimeError(completed.stderr[-2000:] or completed.stdout[-2000:])
    return extract_json(completed.stdout)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--provider", choices=["codex", "claude", "gemini"], required=True)
    parser.add_argument("--limit", type=int, default=1)
    parser.add_argument("--family", default="direct_r_effect_size_extraction")
    parser.add_argument("--run-id", default="")
    parser.add_argument("--timeout", type=int, default=180)
    parser.add_argument("--max-budget-usd", default="0.50")
    parser.add_argument("--model-selector", default="", help="Exact CLI model selector, e.g. sonnet, opus, gpt-5.5, gemini-2.5-pro.")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--register", action="store_true")
    args = parser.parse_args()

    template_rows = read_csv(TEMPLATE)
    candidates = [
        row
        for row in template_rows
        if row["scoring_eligibility"].startswith("eligible_after_locked_llm_output")
        and row["denominator_family"] == args.family
    ][: args.limit]

    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    cli_meta = {
        "codex": ("openai", "codex_cli", subprocess.run(["codex", "--version"], text=True, capture_output=True).stdout.strip()),
        "claude": ("anthropic", "claude_code", subprocess.run(["claude", "--version"], text=True, capture_output=True).stdout.strip()),
        "gemini": ("google", "gemini_cli", subprocess.run(["gemini", "--version"], text=True, capture_output=True).stdout.strip()),
    }
    model_provider, cli_id, cli_version = cli_meta[args.provider]
    model_id = f"{args.provider}:{args.model_selector}" if args.model_selector else f"{cli_id}:default_unspecified"
    model_version = f"{cli_version}; model_selector={args.model_selector or 'default_unspecified'}"
    run_id = args.run_id or f"paper2_{args.provider}_smoke_{now.replace(':', '').replace('-', '')}_{uuid.uuid4().hex[:8]}"

    output_rows = []
    for row in candidates:
        model_result = {
            "model_answer": "",
            "model_answer_normalized": "",
            "model_source_locator": "",
            "model_source_quote": "",
            "model_confidence": "",
            "abstained": "true",
            "error_code": "dry_run",
            "notes": "",
        }
        if not args.dry_run:
            try:
                if args.provider == "codex":
                    model_result = run_codex(prompt_for(row), args.timeout, args.model_selector)
                elif args.provider == "claude":
                    model_result = run_claude(prompt_for(row), args.timeout, args.max_budget_usd, args.model_selector)
                else:
                    model_result = run_gemini(prompt_for(row), args.timeout, args.model_selector)
            except Exception as exc:  # Preserve row-level failure as locked output evidence.
                model_result = {
                    "model_answer": "",
                    "model_answer_normalized": "",
                    "model_source_locator": "",
                    "model_source_quote": "",
                    "model_confidence": "",
                    "abstained": "true",
                    "error_code": "model_cli_error",
                    "notes": str(exc)[:500],
                }

        locked_row = dict(row)
        locked_row.update(
            {
                "run_id": run_id,
                "model_provider": model_provider,
                "model_id": model_id,
                "model_version": model_version,
                "procedure_id": "raw_model_extraction_smoke",
                "prompt_version": PROMPT_VERSION,
                "run_timestamp_utc": now,
                "temperature": "0",
                "seed": "",
                "model_answer": model_result.get("model_answer", ""),
                "model_answer_normalized": model_result.get("model_answer_normalized", ""),
                "model_source_locator": model_result.get("model_source_locator", ""),
                "model_source_quote": model_result.get("model_source_quote", ""),
                "model_confidence": model_result.get("model_confidence", ""),
                "abstained": model_result.get("abstained", ""),
                "error_code": model_result.get("error_code", ""),
                "raw_output_ref": "not_persisted_smoke",
                "locked_answer_status": "locked",
                "lock_timestamp_utc": now,
                "locked_by": f"{args.provider}_cli_noninteractive",
                "notes": model_result.get("notes", ""),
            }
        )
        output_rows.append(locked_row)

    output = OUTPUT_DIR / f"{run_id}.csv"
    write_csv(output, output_rows, list(template_rows[0].keys()))
    if args.register:
        register_locked_output(output)
    print(output)
    print(f"rows={len(output_rows)}")
    print(f"registered={args.register}")


if __name__ == "__main__":
    main()
